### ISSUE TITLE
Installation Instructions Dont Work.

### ISSUE THREAD

**Issue by idkjs** [auth0/relay-auth#2]
OSX 10.11.
Node 7.3 and 6.3

Debug log. Clearly its something you expect me to know. I apologize for my ignorance.

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/Users/klik/.nvm/versions/node/v7.3.0/bin/node',
1 verbose cli   '/Users/klik/.nvm/versions/node/v7.3.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle simple-relay-starter@1.2.1~prebuild: simple-relay-starter@1.2.1
6 silly lifecycle simple-relay-starter@1.2.1~prebuild: no script for prebuild, continuing
7 info lifecycle simple-relay-starter@1.2.1~build: simple-relay-starter@1.2.1
8 verbose lifecycle simple-relay-starter@1.2.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle simple-relay-starter@1.2.1~build: PATH: /Users/klik/.nvm/versions/node/v7.3.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/klik/Projects/GraphQL-Projects/relay-auth/node_modules/.bin:/Users/klik/.nvm/versions/node/v7.3.0/bin:/Users/klik/.pyenv/shims:/Users/klik/.avn/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin/:/Users/klik/google-cloud-sdk/bin:/Users/klik/.rbenv/shims:/Users/klik/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/klik/.rvm/bin:/Users/klik/.rvm/bin
10 verbose lifecycle simple-relay-starter@1.2.1~build: CWD: /Users/klik/Projects/GraphQL-Projects/relay-auth
11 silly lifecycle simple-relay-starter@1.2.1~build: Args: [ '-c', 'npm run build:schema && npm run build:browser' ]
12 silly lifecycle simple-relay-starter@1.2.1~build: Returned: code: 1  signal: null
13 info lifecycle simple-relay-starter@1.2.1~build: Failed to exec build script
14 verbose stack Error: simple-relay-starter@1.2.1 build: `npm run build:schema && npm run build:browser`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/klik/.nvm/versions/node/v7.3.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/klik/.nvm/versions/node/v7.3.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid simple-relay-starter@1.2.1
16 verbose cwd /Users/klik/Projects/GraphQL-Projects/relay-auth
17 error Darwin 15.6.0
18 error argv "/Users/klik/.nvm/versions/node/v7.3.0/bin/node" "/Users/klik/.nvm/versions/node/v7.3.0/bin/npm" "run" "build"
19 error node v7.3.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error simple-relay-starter@1.2.1 build: `npm run build:schema && npm run build:browser`
22 error Exit status 1
23 error Failed at the simple-relay-starter@1.2.1 build script 'npm run build:schema && npm run build:browser'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the simple-relay-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:schema && npm run build:browser
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs simple-relay-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls simple-relay-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by chenkie** [comment]
Likely it's that the deps are outdated, you're not doing anything wrong :)

Have a look at the starter project I worked from. It looks to have been updated more recently: https://github.com/mhart/simple-relay-starter

**Comment by idkjs** [comment]
Ok. Will do. Thanks
